poj/urls.py
#!/usr/bin/env python
# encoding: utf-8


from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.show, name='show'),
        url(r'^(?P<username>\w+)/$', views.detail, name='detail'),
        ]

visualweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'visualweb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.index, name="index"),
    url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^poll/', include('poll.urls', namespace='poll')),
    url(r'^algorithm/', include('algorithm.urls', namespace='algorithm')),
    url(r'^poj/', include('poj.urls', namespace='poj')),
    url(r'^wangyi/', include('wangyi.urls', namespace='wangyi')),
    url(r'^admin/', include(admin.site.urls)),
]

poj/models.py
from django.db import models

# Create your models here.

poj/views.py
from django.shortcuts import render
import sqlite3


def show(request):
    conn = sqlite3.connect('poj/recommend.db')
    cur = conn.cursor()
    sql = "select * from recommend limit 100"
    cur.execute(sql)
    data = cur.fetchall()
    username = []
    for item in data:
        username.append(item[1])
    return render(request, 'poj/show.html',
            {
                'username': username,
            }
    )


def detail(request, username):
    print username
    conn = sqlite3.connect('poj/recommend.db')
    cur = conn.cursor()
    sql = "select * from recommend where username = ?"
    cur.execute(sql, (username,))
    problem = cur.fetchone()[2]
    print sql
    print problem
    return render(request, 'poj/detail.html',
            {
                'problem': problem,
                'username': username,
            }
    )

templates/poj/detail.html
{% extends "base.html" %}
{% block title %} Recommend Success {% endblock %}
{% block css %}
<style>
    h2, p {
        color: black;
        "text-align: center;
    }
    p {
        font-size: 25px;
    }
</style>
{% endblock %}
{% block content %}

<div class="container" style="width: 100%; color: black;">
    <h2>Recommend Problem</h2>
    <p>Username:    {{ username }}</p>
    <p>Problem:   {{ problem }}</p>
</div>


{% endblock%}

templates/poj/show.html
{% extends "base.html" %}
{% block title %} Poj Recommend {% endblock %}
{% block css %}
<style>
    div, a {
        color: black;
    }
</style>
{% endblock %}
{% block content %}

<div class="container">
    <h2 style="text-align: center;">Poj Problem Recommendation</h2>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Username</th>
            </tr>
        </thead>
        {% if username %}
        <tbody>
        {% for row in username %}
            <tr>
                <td><a href="{% url 'poj:detail' row %}">{{ row }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
        {% endif %}
    </table>
</div>

{% endblock %}