poj/urls.py
#!/usr/bin/env python
# encoding: utf-8


from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.show, name='show'),
        url(r'^(?P<username>\w+)/$', views.detail, name='detail'),
        ]

poll/urls.py
#!/usr/bin/env python
# encoding: utf-8


from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
        url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
        url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
        url(r'^base/$', views.base, name='base'),
        url(r'^list/$', views.listing, name="listing"),
        ]

visualweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'visualweb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.index, name="index"),
    url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^poll/', include('poll.urls', namespace='poll')),
    url(r'^algorithm/', include('algorithm.urls', namespace='algorithm')),
    url(r'^poj/', include('poj.urls', namespace='poj')),
    url(r'^wangyi/', include('wangyi.urls', namespace='wangyi')),
    url(r'^admin/', include(admin.site.urls)),
]

poll/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default='1900-00-00 00:00:00')
    description = models.CharField(max_length=1000, default='')

    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    vote_date = models.DateTimeField('date vote', default='1900-00-00 00:00:00')


    def __unicode__(self):
        return self.choice_text

poll/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import Template, Context
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import MySQLdb

from .models import Question, Choice

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list' : latest_question_list}
    return render(request, 'poll/css.html', context)


def listing(request):
    question_list = Question.objects.all()
    paginator = Paginator(question_list, 1)

    page = request.GET.get('page')
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)

    return render_to_response('poll/listing.html', {"questions": questions})





def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/detail.html', {'question' : question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/results.html', {'question': question})


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'poll/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
            })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll:results', args=(p.id,)))


def base(request):
    return render(request, 'index.html')

templates/poll/css.html
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Full Screen Page</title>
<style>
    html {
        background: url('/static/poll/images/bg.jpg') no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
    .container {
        border: 1px solid;
        background: black;
        width: 50%;
        height: 5000px;
        padding-left: 10px;
        margin: auto;
    }
    p {
        color: white;
    }
</style>
</head>
<body>
<div class="container">
    <p>Hello world!</p>
</div>
</body>
</html>

templates/poll/detail.html
{% extends "base.html" %}
{% block title %}detail{% endblock %}
{% block content %}
<h1>{{ question.question_text }}</h1>

{% if error_message  %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="container">
<form action="{% url 'poll:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <div class="row">
        <div class="col-md-1 col-sm-1">
            <div><input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/></div>
        </div>
        <div class="col-md-1 col-sm-1">
            <div><label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label></div>
        </div>
    </div>
    {% endfor %}
    <input type="submit" value="vote">
</form>
</div>
{% endblock %}

templates/poll/index.html
{% extends "base.html" %}
{% block title %} Index Page {% endblock %}
{% block content %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'poll/css/style.css' %}"/>


{% endblock %}

templates/poll/listing.html
{% extends "base.html" %}
{% block title %}detail{% endblock %}
{% block css %}
<style>
    a, span, tr, th {
        color: black;
    }
</style>
{% endblock %}
{% block content %}

<div class="pagination">
    <span class="step-links">
        {% if questions.has_previous %}
        <a href="?page={{ questions.previous_page_number }}">previous</a> 
        {% endif %}

        <span class="current">
            Page {{ questions.number }} of {{ questions.paginator.num_pages }}.
        </span>

        {% if questions.has_next %}
            <a href="?page={{ questions.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% for question in questions.object_list %}
<table class="table table-hover">
    <thead>
        <tr>
            <th>question_text</th>
            <th>pub_date</th>
            <th>description</th>
        </tr>
    </thead>
    <tbody>
        <tr>
        <td>{{ question.question_text }}</td>
        <td>{{ question.pub_date }}</td>
        <td>{{ question.description }}</td>
        </tr>
    </tbody>
</table>
{% endfor %}

{% endblock %}

templates/poll/results.html
{% extends "base.html" %}
{% block result %}{% endblock %}
{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
    {% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id%}">Vote again?</a>
{% endblock %}