poj/urls.py
#!/usr/bin/env python
# encoding: utf-8


from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.show, name='show'),
        url(r'^(?P<username>\w+)/$', views.detail, name='detail'),
        ]

upload/urls.py
#!/usr/bin/env python
# encoding: utf-8


from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.upload, name='upload'),
        ]

visualweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'visualweb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', views.index, name="index"),
    url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^poll/', include('poll.urls', namespace='poll')),
    url(r'^algorithm/', include('algorithm.urls', namespace='algorithm')),
    url(r'^poj/', include('poj.urls', namespace='poj')),
    url(r'^wangyi/', include('wangyi.urls', namespace='wangyi')),
    url(r'^admin/', include(admin.site.urls)),
]

upload/models.py
from django.db import models


class Document(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')
    # datetime = models.DateTimeField()

upload/forms.py
#!/usr/bin/env python
# encoding: utf-8


from django import forms


class DocumentForm(forms.Form):
    docfile = forms.FileField(
            label='Select a file',
            help_text='max 100M'
    )

upload/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext

from .models import Document
from .forms import DocumentForm


def upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile=request.FILES['docfile'])
            newdoc.save()
            return render(request, 'upload/success.html')
    else:
        form = DocumentForm()

    documents = Document.objects.all()
    return render_to_response('upload/upload.html',
            {
                'documents': documents,
                'form': form,
            },
            context_instance=RequestContext(request)
    )

templates/upload/success.html
{% extends "base.html" %}
{% block title %} success {% endblock %}
{% block css %}
<style>
    p, a {
        color: black;
    }
</style>
{% endblock %}
{% block content %}


<div class="container">
    <div class="row">
        <p>Upload successed!</p>
        <p><a href="{% url 'upload:upload' %}">click to back</a></p>
    </div>

</div>

{% endblock %}

templates/upload/upload.html
{% extends "base.html" %}
{% block title %} upload {% endblock %}
{% block content %}

<div style="background: #0c0">
{% if error_message  %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<div class="container" style="background: #0c0">
    <div class="row">
        {% if documents %}
        <ul>
        {% for document in documents %}
        <td class="col-md-9 col-sm-9"><li style="color: black">{{ document.docfile.name }}</li></td>
        <!--<td>{{ document.datetime }}</td>-->
        {% endfor %}
        </ul>
        {% else %}
        <div class="col-md-9 col-sm-9"><p>No documents.</p></div>
        {% endif %}
    </div>
</div>



<div class="container" style="font-size: 20px">
<form action="{% url 'upload:upload' %}" method="post" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
    <div class="row">
        <div class="form-group">
            <div class="col-md-9 col-sm-9">
                <div>{{ form.non_field_errors }}</div>
            </div>
        </div>
        <div class="form-group" style="color: black">
            <div class="col-md-9 col-sm-9">
                <div>{{ form.docfile.label_tag }}{{ form.docfile.help_text }}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-9 col-sm-9">
                <div>{{ form.docfile.errors }}</div>
                <div>{{ form.docfile }}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6 col-sm-6">
                <div><button type="submit" class="btn btn-primary" style="background: black; color: #090">Upload</button></div>
            </div>
        </div>
    </div>
</form>
</div>


</div>

{% endblock %}